n = input('Dígite algo: ')
print('O tipo primitivo desse valor é', type(n))
print('É um número?', n.isnumeric())
print('É alpha númerico? ', n.isalnum())
print('É alpha letra? ', n.isalpha())
print('Está em maiúsculas? ', n.isupper())
print('Está em minúsculas', n.islower())
print('Está capitalizada?', n.istitle())
print('Só tem espaços?', n.isspace())
